wandb_version: 1

T:
  desc: null
  value: 4
T_mult:
  desc: null
  value: 2
T_warmup:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    cli_version: 0.10.29
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      4: 3.7.7
      5: 0.10.29
      8:
      - 5
aug:
  desc: null
  value: 'no'
batch_size:
  desc: null
  value: 8
enc:
  desc: null
  value: timm-regnety_320
enc_weights:
  desc: null
  value: imagenet
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0001
loss:
  desc: null
  value: CE
loss_weight:
  desc: null
  value: 0.5
lr_max:
  desc: null
  value: 0.0001
lr_max_decay:
  desc: null
  value: 0.8
lr_min:
  desc: null
  value: 1.0e-06
lr_scheduler:
  desc: null
  value: SGDR
model:
  desc: null
  value: DeepLabV3Plus
optimizer:
  desc: null
  value: Adam
weight_decay:
  desc: null
  value: 1.0e-06
